In [1]:
#April 22, 2026
#Charlotte Meyer
#Data Seminar
#This code is meant to use statsmodels to create a logistic regression

In [2]:
#importing packages
import statsmodels.api
import pandas as pd
import statsmodels.formula.api as smf
from statsmodels.formula.api import ols
import numpy as np
#import statsmodels.api as sm
from statsmodels.tools.tools import add_constant
from sklearn.model_selection import train_test_split

In [3]:
#reading in the data 
cejst = pd.read_csv("cejst_logistic_regression.csv", index_col=0, low_memory=False)

#setting pandas columns so I can see all of them
pd.set_option('display.max_columns', None)

In [4]:
#making a function that will split columns into bins for fixed effects

def split_into_bins(fixed_effect_column):

    #cut into 11 bins (arbitrary)
    #using cut, NOT qcut
    cejst[fixed_effect_column + "_bin"] = pd.cut(cejst[fixed_effect_column], 11, labels=range(1,12))
    
    #creating dummies, prefix adds column in front of bin name
    dummies = pd.get_dummies(cejst[fixed_effect_column + "_bin"])#, prefix=fixed_column_effect)
    
    #removing middle dummy
    dummies = dummies[[i for i in dummies.columns if i != 6]]
    
    #renaming dummies
    dummies.columns = [fixed_effect_column + "_" + str(i) for i in dummies.columns ]
    
    #combining existing columns with cejst
#    dummies[fixed_effect_column] = cejst[fixed_effect_column]
#    dummies['has_datacenter'] = cejst['has_datacenter']

    #drop na
    dummies = dummies.dropna()
    
    #viewing bins
    return dummies
#    return cejst.groupby('bin')[[fixed_effect_column, 'has_datacenter']].mean() #this shows the bins; will show bin 6

In [5]:
linguistic_isolation_dummies = split_into_bins("linguistic_isolation")
linguistic_isolation_dummies

#cejst = cejst.copy()
cejst = pd.concat([cejst, linguistic_isolation_dummies], axis=1)

/var/folders/sl/dyq7sj0x2_z0dr2x82v1ln_80000gn/T/ipykernel_34180/23027534.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cejst[fixed_effect_column + "_bin"] = pd.cut(cejst[fixed_effect_column], 11, labels=range(1,12))

In [6]:
perc_poverty_dummies = split_into_bins("perc_poverty")
perc_poverty_dummies

cejst = pd.concat([cejst, perc_poverty_dummies], axis=1)

/var/folders/sl/dyq7sj0x2_z0dr2x82v1ln_80000gn/T/ipykernel_34180/23027534.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  cejst[fixed_effect_column + "_bin"] = pd.cut(cejst[fixed_effect_column], 11, labels=range(1,12))

In [7]:
cejst

,GEOID,County Name,State,perc_black,perc_native_american,perc_asian,perc_hawaiin_pacific,perc_mixed_race,perc_white,perc_hispanic,Percent other races,perc_children,Percent age 10 to 64,perc_elderly,Total threshold criteria exceeded,Total categories exceeded,Identified as disadvantaged without considering neighbors,Identified as disadvantaged based on neighbors and relaxed low income threshold only,Identified as disadvantaged due to tribal overlap,Identified as disadvantaged,perc_disadvantaged,Share of neighbors that are identified as disadvantaged,Identified as disadvantaged in v1.0,Identified as disadvantaged solely due to status in v1.0 (grandfathered),population,Interpolated number of off-campus students in poverty,Adjusted percent of individuals below 200% Federal Poverty Line (percentile),perc_poverty,Is low income?,Income data has been estimated based on geographic neighbor income,Greater than or equal to the 90th percentile for expected agriculture loss rate and is low income?,Expected agricultural loss rate (Natural Hazards Risk Index) (percentile),Expected agricultural loss rate (Natural Hazards Risk Index),Greater than or equal to the 90th percentile for expected building loss rate and is low income?,Expected building loss rate (Natural Hazards Risk Index) (percentile),Expected building loss rate (Natural Hazards Risk Index),Greater than or equal to the 90th percentile for expected population loss rate and is low income?,Expected population loss rate (Natural Hazards Risk Index) (percentile),loss_rate,Share of properties at risk of flood in 30 years (percentile),flood_risk,Greater than or equal to the 90th percentile for share of properties at risk of flood in 30 years,Greater than or equal to the 90th percentile for share of properties at risk of flood in 30 years and is low income?,Share of properties at risk of fire in 30 years (percentile),Share of properties at risk of fire in 30 years,Greater than or equal to the 90th percentile for share of properties at risk of fire in 30 years,Greater than or equal to the 90th percentile for share of properties at risk of fire in 30 years and is low income?,Greater than or equal to the 90th percentile for energy burden and is low income?,Energy burden (percentile),energy_burden,Greater than or equal to the 90th percentile for PM2.5 exposure and is low income?,PM2.5 in the air (percentile),pm_air,Greater than or equal to the 90th percentile for diesel particulate matter and is low income?,Diesel particulate matter exposure (percentile),diesel_exposure,Greater than or equal to the 90th percentile for traffic proximity and is low income?,Traffic proximity and volume (percentile),traffic_prox,Greater than or equal to the 90th percentile for DOT transit barriers and is low income?,travel_barriers,Greater than or equal to the 90th percentile for housing burden and is low income?,Housing burden (percent) (percentile),housing_burden,"Greater than or equal to the 90th percentile for lead paint, the median house value is less than 90th percentile and is low income?",Percent pre-1960s housing (lead paint indicator) (percentile),Percent pre-1960s housing (lead paint indicator),Median value ($) of owner-occupied housing units (percentile),house_value,Greater than or equal to the 90th percentile for share of the tract's land area that is covered by impervious surface or cropland as a percent and is low income?,Greater than or equal to the 90th percentile for share of the tract's land area that is covered by impervious surface or cropland as a percent,Share of the tract's land area that is covered by impervious surface or cropland as a percent,pavement_cropland,Does the tract have at least 35 acres in it?,Tract experienced historic underinvestment and remains low income,Tract experienced historic underinvestment,no_plumbing,Share of homes with no kitchen or indoor plumbing (percent),Greater than or equal to the 90th percentile for proximity to hazardous waste facilities and is low income?,Proximity to hazardous waste sites (percentile),hazard_waste_prox,Greater than or equal to the 90th percentile for proximity to superfund sites and is low income?,Proximity to NPL (Superfund) sites (percentile),superfund_prox,Greater than or equal to the 90th percentile for proximity to RMP sites and is low income?,Proximity to Risk Management Plan (RMP) facilities (percentile),risk_facilities_prox,Is there at least one Formerly Used Defense Site (FUDS) in the tract?,Is there at least one abandoned mine in this census tract?,There is at least one abandoned mine in this census tract and the tract is low income.,There is at least one Formerly Used Defense Site (FUDS) in the tract and the tract is low income.,"Is there at least one Formerly Used Defense Site (FUDS) in the tract, where missing data is treated as False?","Is there at least one abandoned mine in this census tract, where missing data is treated as False?",Greater than or equal to the 90th percentile for wastewater discharge and is low income?,wastewater_discharge,Wastewater discharge,Greater than or equal to the 90th percentile for leaky underground storage tanks and is low income?,leaky_storage_tanks,Leaky underground storage tanks,Greater than or equal to the 90th percentile for asthma and is low income?,asthma,Current asthma among adults aged greater than or equal to 18 years,Greater than or equal to the 90th percentile for diabetes and is low income?,diabetes,Diagnosed diabetes among adults aged greater than or equal to 18 years,Greater than or equal to the 90th percentile for heart disease and is low income?,heart_disease,Coronary heart disease among adults aged greater than or equal to 18 years,Greater than or equal to the 90th percentile for low life expectancy and is low income?,Low life expectancy (percentile),life_expectancy,Greater than or equal to the 90th percentile for low median household income as a percent of area median income and has low HS attainment?,Low median household income as a percent of area median income (percentile),household_income_compared,Greater than or equal to the 90th percentile for households in linguistic isolation and has low HS attainment?,linguistic_isolation,Linguistic isolation (percent),Greater than or equal to the 90th percentile for unemployment and has low HS attainment?,Unemployment (percent) (percentile),perc_unemployment,Greater than or equal to the 90th percentile for households at or below 100% federal poverty level and has low HS attainment?,Percent of individuals below 200% Federal Poverty Line (percentile),Percent of individuals below 200% Federal Poverty Line,Percent of individuals < 100% Federal Poverty Line (percentile),Percent of individuals < 100% Federal Poverty Line,Percent individuals age 25 or over with less than high school degree (percentile),no_hs_degree,Percent of residents who are not currently enrolled in higher ed,Unemployment (percent) in 2019 (island areas) and 2010 (states and PR),Percentage households below 100% of federal poverty line in 2019 (island areas) and 2010 (states and PR),Greater than or equal to the 90th percentile for unemployment and has low HS education in 2019 (island areas)?,Greater than or equal to the 90th percentile for households at or below 100% federal poverty level and has low HS education in 2019 (island areas)?,Greater than or equal to the 90th percentile for low median household income as a percent of area median income and has low HS education in 2019 (island areas)?,Number of Tribal areas within Census tract for Alaska,Names of Tribal areas within Census tract,Percent of the Census tract that is within Tribal areas,has_datacenter,linguistic_isolation_bin,linguistic_isolation_1,linguistic_isolation_2,linguistic_isolation_3,linguistic_isolation_4,linguistic_isolation_5,linguistic_isolation_7,linguistic_isolation_8,linguistic_isolation_9,linguistic_isolation_10,linguistic_isolation_11,perc_poverty_bin,perc_poverty_1,perc_poverty_2,perc_poverty_3,perc_poverty_4,perc_poverty_5,perc_poverty_7,perc_poverty_8,perc_poverty_9,perc_poverty_10,perc_poverty_11
0,1001020100,Autauga County,Alabama,0.07,0.0,0.00,0.00,0.07,0.83,0.01,0.00,0.10,0.76,0.13,0,0.0,False,False,NaN,False,0,0.0,False,False,1993.0,9.90,0.49,0.29,False,False,False,45.0,0.0776,False,66.0,0.0253,False,76.0,0.0004,87.0,22.0,False,False,84.0,67.0,False,False,False,49.0,2.0,False,67.0,9.15,False,33.0,0.17,False,15.0,35.91,False,70.0,False,50.0,22.0,False,41.0,17.0,30.0,136100.0,False,False,760.0,10.0,True,False,NaN,0.52,0.00,False,42.0,0.50,False,52.0,0.06,False,11.0,0.07,NaN,NaN,False,False,False,False,False,NaN,NaN,False,26.0,0.41,False,57.0,990.0,False,60.0,1130.0,False,59.0,640.0,False,89.0,73.09,False,29.0,114.0,False,12.0,0.0,False,22.0,2.0,False,44.0,27.0,66.0,16.0,60.0,12.0,91.0,2.0,10.0,False,False,False,NaN,NaN,NaN,0,1,True,False,False,False,False,False,False,False,False,False,4,False,False,False,True,False,False,False,False,False,False
1,1001020200,Autauga County,Alabama,0.57,0.0,0.00,0.01,0.02,0.38,0.01,0.00,0.12,0.73,0.14,0,0.0,False,False,NaN,False,0,0.0,False,False,1959.0,6.83,0.75,0.44,True,False,False,21.0,0.0053,False,69.0,0.0278,False,65.0,0.0003,89.0,25.0,False,False,77.0,23.0,False,False,False,6.0,1.0,False,68.0,9.18,False,37.0,0.19,False,36.0,159.74,False,88.0,False,56.0,24.0,False,43.0,19.0,13.0,90500.0,False,False,2058.0,26.0,True,False,NaN,0.21,0.00,False,50.0,0.81,False,55.0,0.07,False,12.0,0.08,NaN,NaN,False,False,False,False,False,NaN,NaN,False,57.0,2.46,False,82.0,1100.0,False,83.0,1420.0,False,49.0,590.0,False,65.0,76.90,False,61.0,83.0,False,12.0,0.0,False,44.0,4.0,False,72.0,43.0,72.0,19.0,68.0,14.0,96.0,5.0,14.0,False,False,False,NaN,NaN,NaN,0,1,True,False,False,False,False,False,False,False,False,False,5,False,False,False,False,True,False,False,False,False,False
2,1001020300,Autauga County,Alabama,0.24,0.0,0.00,0.00,0.02,0.65,0.06,0.06,0.12,0.71,0.16,0,0.0,False,False,NaN,False,0,0.0,False,False,3507.0,0.00,0.51,0.29,False,False,False,39.0,0.0527,False,54.0,0.0163,False,59.0,0.0002,48.0,7.0,False,False,78.0,32.0,False,False,False,68.0,3.0,False,68.0,9.20,False,45.0,0.22,False,37.0,169.97,False,50.0,False,46.0,21.0,False,22.0,5.0,25.0,122600.0,False,False,2353.0,29.0,True,False,NaN,0.21,0.00,False,59.0,1.29,False,57.0,0.07,False,12.0,0.08,NaN,NaN,False,False,False,False,False,NaN,NaN,False,52.0,1.98,False,65.0,1019.0,False,66.0,1180.0,False,60.0,650.0,False,NaN,NaN,False,38.0,105.0,False,12.0,0.0,False,32.0,3.0,False,47.0,29.0,68.0,17.0,68.0,14.0,97.0,5.0,8.0,False,False,False,NaN,NaN,NaN,0,1,True,False,False,False,False,False,False,False,False,False,4,False,False,False,True,False,False,False,False,False,False
3,1001020400,Autauga County,Alabama,0.05,0.0,0.00,0.00,0.03,0.89,0.01,0.00,0.10,0.65,0.24,0,0.0,False,False,NaN,False,0,0.0,False,False,3878.0,0.00,0.36,0.22,False,False,False,43.0,0.0698,False,55.0,0.0174,False,62.0,0.0002,61.0,9.0,False,False,78.0,29.0,False,False,False,63.0,3.0,False,69.0,9.23,False,55.0,0.27,False,64.0,500.54,False,17.0,False,28.0,16.0,False,31.0,11.0,36.0,152700.0,False,False,2333.0,29.0,True,False,NaN,0.65,0.00,False,69.0,2.05,False,60.0,0.08,False,13.0,0.08,False,NaN,False,False,False,False,False,NaN,NaN,False,65.0,3.36,False,27.0,880.0,False,55.0,1080.0,False,66.0,680.0,False,77.0,75.40,False,30.0,113.0,False,58.0,2.0,False,27.0,3.0,False,31.0,21.0,15.0,4.0,41.0,8.0,94.0,3.0,6.0,False,False,False,NaN,NaN,NaN,0,6,False,False,False,False,False,False,False,False,False,False,3,False,False,True,False,False,False,False,False,False,False
4,1001020500,Autauga County,Alabama,0.18,0.0,0.03,0.00,0.02,0.70,0.04,0.00,0.11,0.74,0.13,0,0.0,False,False,NaN,False,0,0.0,False,False,10596.0,222.48,0.29,0.19,False,False,False,53.0,0.1419,False,55.0,0.0171,False,61.0,0.0002,25.0,3.0,False,False,73.0,5.0,False,False,False,38.0,2.0,False,69.0,9.24,False,61.0,0.30,False,43.0,220.21,False,6.0,False,46.0,21.0,False,1.0,0.0,48.0,186900.0,False,False,3955.0,51.0,True,False,NaN,0.95,0.04,False,56.0,1.08,False,64.0,0.09,False,13.0,0.09,NaN,NaN,False,False,False,False,False,10.0,0.0,False,55.0,2.22,False,37.0,919.0,False,34.0,919.0,False,31.0,500.0,False,41.0,79.40,False,22.0,125.0,False,54.0,1.0,False,26.0,3.0,False,29.0,20.0,62.0,15.0,40.0,7.0,94.0,2.0,5.0,False,False,False,NaN,NaN,NaN,0,6,False,False,False,False,False,False,False,False,False,False,3,False,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74129,78030960900,NaN,Virgin Islands,0.71,0.0,0.02,0.00,0.11,0.11,0.13,0.02,NaN,NaN,NaN,1,1.0,True,True,NaN,True,100,100.0,False,False,3721.0,NaN,NaN,NaN,True,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,False,False,NaN,NaN,False,False,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,True,NaN,False,True,True,False,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,25.0,False,False,False,NaN,NaN,NaN,0,NaN,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False
74130,78030961000,NaN,Virgin Islands,0.78,0.0,0.01,0.00,0.11,0.04,0.23,0.02,NaN,NaN,NaN,1,1.0,True,False,NaN,True,100,80.0,False,False,4386.0,NaN,NaN,NaN,True,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,False,False,NaN,NaN,False,False,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,False,False,False,False,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,27.0,True,False,False,NaN,NaN,NaN,0,NaN,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False
74131,78030961100,NaN,Virgin Islands,0.80,0.0,0.02,0.00,0.11,0.02,0.16,0.03,NaN,NaN,NaN,2,1.0,True,False,NaN,True,100,75.0,False,False,3780.0,NaN,NaN,NaN,True,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,False,False,NaN,NaN,False,False,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,False,False,False,False,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,28.0,True,False,True,NaN,NaN,NaN,0,NaN,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False
74132,78030961200,NaN,Virgin Islands,0.79,0.0,0.01,0.00,0.09,0.04,0.18,0.04,NaN,NaN,NaN,2,1.0,True,False,NaN,True,100,75.0,True,False,2118.0,NaN,NaN,NaN,True,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,False,False,NaN,NaN,False,False,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,False,False,False,False,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,32.0,True,False,True,NaN,NaN,NaN,0,NaN,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False
74133,78030990000,NaN,Virgin Islands,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.0,False,False,NaN,False,0,71.0,False,False,0.0,NaN,NaN,NaN,False,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,False,False,NaN,NaN,False,False,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,NaN,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,False,False,False,False,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False,False,NaN,NaN,NaN,0,NaN,False,False,False,False,False,False,False,False,False,False,NaN,False,False,False,False,False,False,False,False,False,False

In [8]:
# Define predictor variables
predictors = ['perc_white', 'perc_poverty', 'pm_air', 'perc_unemployment', 
              'hazard_waste_prox', 'life_expectancy', 'perc_hispanic', 
              'perc_elderly', 'perc_children', 'perc_disadvantaged', 
              'population', 'loss_rate', 'flood_risk', 'energy_burden', 
              'diesel_exposure', 'traffic_prox', 'travel_barriers', 
              'housing_burden', 'house_value', 'pavement_cropland', 
              'no_plumbing', 'superfund_prox', 
              'asthma', 'diabetes', 'heart_disease', 'household_income_compared', 
              'linguistic_isolation', 'no_hs_degree']

print(cejst[predictors].isnull().sum())
#removing wastewater_discharge from predictors because it has 20,000 NA's

perc_white                    744
perc_poverty                  158
pm_air                       1875
perc_unemployment             973
hazard_waste_prox             158
life_expectancy              6986
perc_hispanic                 744
perc_elderly                  861
perc_children                 861
perc_disadvantaged              0
population                     28
loss_rate                    1604
flood_risk                    796
energy_burden                1054
diesel_exposure               739
traffic_prox                 2834
travel_barriers              1801
housing_burden               1158
house_value                  2201
pavement_cropland            1595
no_plumbing                  1158
superfund_prox                158
asthma                       3821
diabetes                     3821
heart_disease                3821
household_income_compared    5021
linguistic_isolation         1932
no_hs_degree                  879
dtype: int64

In [9]:
#dropping NA's; code is from Claude


#dropping all rows with NaN in predictor columns
cejst = cejst.dropna(subset=predictors)

#verify they match
print(f"X shape: {cejst[predictors].shape}, y shape: {cejst["has_datacenter"].shape}")
#verify no na's
print(cejst[predictors].isnull().sum())

X shape: (59078, 28), y shape: (59078,)
perc_white                   0
perc_poverty                 0
pm_air                       0
perc_unemployment            0
hazard_waste_prox            0
life_expectancy              0
perc_hispanic                0
perc_elderly                 0
perc_children                0
perc_disadvantaged           0
population                   0
loss_rate                    0
flood_risk                   0
energy_burden                0
diesel_exposure              0
traffic_prox                 0
travel_barriers              0
housing_burden               0
house_value                  0
pavement_cropland            0
no_plumbing                  0
superfund_prox               0
asthma                       0
diabetes                     0
heart_disease                0
household_income_compared    0
linguistic_isolation         0
no_hs_degree                 0
dtype: int64

In [10]:
cejst

,GEOID,County Name,State,perc_black,perc_native_american,perc_asian,perc_hawaiin_pacific,perc_mixed_race,perc_white,perc_hispanic,Percent other races,perc_children,Percent age 10 to 64,perc_elderly,Total threshold criteria exceeded,Total categories exceeded,Identified as disadvantaged without considering neighbors,Identified as disadvantaged based on neighbors and relaxed low income threshold only,Identified as disadvantaged due to tribal overlap,Identified as disadvantaged,perc_disadvantaged,Share of neighbors that are identified as disadvantaged,Identified as disadvantaged in v1.0,Identified as disadvantaged solely due to status in v1.0 (grandfathered),population,Interpolated number of off-campus students in poverty,Adjusted percent of individuals below 200% Federal Poverty Line (percentile),perc_poverty,Is low income?,Income data has been estimated based on geographic neighbor income,Greater than or equal to the 90th percentile for expected agriculture loss rate and is low income?,Expected agricultural loss rate (Natural Hazards Risk Index) (percentile),Expected agricultural loss rate (Natural Hazards Risk Index),Greater than or equal to the 90th percentile for expected building loss rate and is low income?,Expected building loss rate (Natural Hazards Risk Index) (percentile),Expected building loss rate (Natural Hazards Risk Index),Greater than or equal to the 90th percentile for expected population loss rate and is low income?,Expected population loss rate (Natural Hazards Risk Index) (percentile),loss_rate,Share of properties at risk of flood in 30 years (percentile),flood_risk,Greater than or equal to the 90th percentile for share of properties at risk of flood in 30 years,Greater than or equal to the 90th percentile for share of properties at risk of flood in 30 years and is low income?,Share of properties at risk of fire in 30 years (percentile),Share of properties at risk of fire in 30 years,Greater than or equal to the 90th percentile for share of properties at risk of fire in 30 years,Greater than or equal to the 90th percentile for share of properties at risk of fire in 30 years and is low income?,Greater than or equal to the 90th percentile for energy burden and is low income?,Energy burden (percentile),energy_burden,Greater than or equal to the 90th percentile for PM2.5 exposure and is low income?,PM2.5 in the air (percentile),pm_air,Greater than or equal to the 90th percentile for diesel particulate matter and is low income?,Diesel particulate matter exposure (percentile),diesel_exposure,Greater than or equal to the 90th percentile for traffic proximity and is low income?,Traffic proximity and volume (percentile),traffic_prox,Greater than or equal to the 90th percentile for DOT transit barriers and is low income?,travel_barriers,Greater than or equal to the 90th percentile for housing burden and is low income?,Housing burden (percent) (percentile),housing_burden,"Greater than or equal to the 90th percentile for lead paint, the median house value is less than 90th percentile and is low income?",Percent pre-1960s housing (lead paint indicator) (percentile),Percent pre-1960s housing (lead paint indicator),Median value ($) of owner-occupied housing units (percentile),house_value,Greater than or equal to the 90th percentile for share of the tract's land area that is covered by impervious surface or cropland as a percent and is low income?,Greater than or equal to the 90th percentile for share of the tract's land area that is covered by impervious surface or cropland as a percent,Share of the tract's land area that is covered by impervious surface or cropland as a percent,pavement_cropland,Does the tract have at least 35 acres in it?,Tract experienced historic underinvestment and remains low income,Tract experienced historic underinvestment,no_plumbing,Share of homes with no kitchen or indoor plumbing (percent),Greater than or equal to the 90th percentile for proximity to hazardous waste facilities and is low income?,Proximity to hazardous waste sites (percentile),hazard_waste_prox,Greater than or equal to the 90th percentile for proximity to superfund sites and is low income?,Proximity to NPL (Superfund) sites (percentile),superfund_prox,Greater than or equal to the 90th percentile for proximity to RMP sites and is low income?,Proximity to Risk Management Plan (RMP) facilities (percentile),risk_facilities_prox,Is there at least one Formerly Used Defense Site (FUDS) in the tract?,Is there at least one abandoned mine in this census tract?,There is at least one abandoned mine in this census tract and the tract is low income.,There is at least one Formerly Used Defense Site (FUDS) in the tract and the tract is low income.,"Is there at least one Formerly Used Defense Site (FUDS) in the tract, where missing data is treated as False?","Is there at least one abandoned mine in this census tract, where missing data is treated as False?",Greater than or equal to the 90th percentile for wastewater discharge and is low income?,wastewater_discharge,Wastewater discharge,Greater than or equal to the 90th percentile for leaky underground storage tanks and is low income?,leaky_storage_tanks,Leaky underground storage tanks,Greater than or equal to the 90th percentile for asthma and is low income?,asthma,Current asthma among adults aged greater than or equal to 18 years,Greater than or equal to the 90th percentile for diabetes and is low income?,diabetes,Diagnosed diabetes among adults aged greater than or equal to 18 years,Greater than or equal to the 90th percentile for heart disease and is low income?,heart_disease,Coronary heart disease among adults aged greater than or equal to 18 years,Greater than or equal to the 90th percentile for low life expectancy and is low income?,Low life expectancy (percentile),life_expectancy,Greater than or equal to the 90th percentile for low median household income as a percent of area median income and has low HS attainment?,Low median household income as a percent of area median income (percentile),household_income_compared,Greater than or equal to the 90th percentile for households in linguistic isolation and has low HS attainment?,linguistic_isolation,Linguistic isolation (percent),Greater than or equal to the 90th percentile for unemployment and has low HS attainment?,Unemployment (percent) (percentile),perc_unemployment,Greater than or equal to the 90th percentile for households at or below 100% federal poverty level and has low HS attainment?,Percent of individuals below 200% Federal Poverty Line (percentile),Percent of individuals below 200% Federal Poverty Line,Percent of individuals < 100% Federal Poverty Line (percentile),Percent of individuals < 100% Federal Poverty Line,Percent individuals age 25 or over with less than high school degree (percentile),no_hs_degree,Percent of residents who are not currently enrolled in higher ed,Unemployment (percent) in 2019 (island areas) and 2010 (states and PR),Percentage households below 100% of federal poverty line in 2019 (island areas) and 2010 (states and PR),Greater than or equal to the 90th percentile for unemployment and has low HS education in 2019 (island areas)?,Greater than or equal to the 90th percentile for households at or below 100% federal poverty level and has low HS education in 2019 (island areas)?,Greater than or equal to the 90th percentile for low median household income as a percent of area median income and has low HS education in 2019 (island areas)?,Number of Tribal areas within Census tract for Alaska,Names of Tribal areas within Census tract,Percent of the Census tract that is within Tribal areas,has_datacenter,linguistic_isolation_bin,linguistic_isolation_1,linguistic_isolation_2,linguistic_isolation_3,linguistic_isolation_4,linguistic_isolation_5,linguistic_isolation_7,linguistic_isolation_8,linguistic_isolation_9,linguistic_isolation_10,linguistic_isolation_11,perc_poverty_bin,perc_poverty_1,perc_poverty_2,perc_poverty_3,perc_poverty_4,perc_poverty_5,perc_poverty_7,perc_poverty_8,perc_poverty_9,perc_poverty_10,perc_poverty_11
0,1001020100,Autauga County,Alabama,0.07,0.00,0.00,0.00,0.07,0.83,0.01,0.00,0.10,0.76,0.13,0,0.0,False,False,NaN,False,0,0.0,False,False,1993.0,9.90,0.49,0.29,False,False,False,45.0,0.0776,False,66.0,0.0253,False,76.0,0.0004,87.0,22.0,False,False,84.0,67.0,False,False,False,49.0,2.0,False,67.0,9.15,False,33.0,0.17,False,15.0,35.91,False,70.0,False,50.0,22.0,False,41.0,17.0,30.0,136100.0,False,False,760.0,10.0,True,False,NaN,0.52,0.00,False,42.0,0.50,False,52.0,0.06,False,11.0,0.07,NaN,NaN,False,False,False,False,False,NaN,NaN,False,26.0,0.41,False,57.0,990.0,False,60.0,1130.0,False,59.0,640.0,False,89.0,73.09,False,29.0,114.0,False,12.0,0.0,False,22.0,2.0,False,44.0,27.0,66.0,16.0,60.0,12.0,91.0,2.0,10.0,False,False,False,NaN,NaN,NaN,0,1,True,False,False,False,False,False,False,False,False,False,4,False,False,False,True,False,False,False,False,False,False
1,1001020200,Autauga County,Alabama,0.57,0.00,0.00,0.01,0.02,0.38,0.01,0.00,0.12,0.73,0.14,0,0.0,False,False,NaN,False,0,0.0,False,False,1959.0,6.83,0.75,0.44,True,False,False,21.0,0.0053,False,69.0,0.0278,False,65.0,0.0003,89.0,25.0,False,False,77.0,23.0,False,False,False,6.0,1.0,False,68.0,9.18,False,37.0,0.19,False,36.0,159.74,False,88.0,False,56.0,24.0,False,43.0,19.0,13.0,90500.0,False,False,2058.0,26.0,True,False,NaN,0.21,0.00,False,50.0,0.81,False,55.0,0.07,False,12.0,0.08,NaN,NaN,False,False,False,False,False,NaN,NaN,False,57.0,2.46,False,82.0,1100.0,False,83.0,1420.0,False,49.0,590.0,False,65.0,76.90,False,61.0,83.0,False,12.0,0.0,False,44.0,4.0,False,72.0,43.0,72.0,19.0,68.0,14.0,96.0,5.0,14.0,False,False,False,NaN,NaN,NaN,0,1,True,False,False,False,False,False,False,False,False,False,5,False,False,False,False,True,False,False,False,False,False
3,1001020400,Autauga County,Alabama,0.05,0.00,0.00,0.00,0.03,0.89,0.01,0.00,0.10,0.65,0.24,0,0.0,False,False,NaN,False,0,0.0,False,False,3878.0,0.00,0.36,0.22,False,False,False,43.0,0.0698,False,55.0,0.0174,False,62.0,0.0002,61.0,9.0,False,False,78.0,29.0,False,False,False,63.0,3.0,False,69.0,9.23,False,55.0,0.27,False,64.0,500.54,False,17.0,False,28.0,16.0,False,31.0,11.0,36.0,152700.0,False,False,2333.0,29.0,True,False,NaN,0.65,0.00,False,69.0,2.05,False,60.0,0.08,False,13.0,0.08,False,NaN,False,False,False,False,False,NaN,NaN,False,65.0,3.36,False,27.0,880.0,False,55.0,1080.0,False,66.0,680.0,False,77.0,75.40,False,30.0,113.0,False,58.0,2.0,False,27.0,3.0,False,31.0,21.0,15.0,4.0,41.0,8.0,94.0,3.0,6.0,False,False,False,NaN,NaN,NaN,0,6,False,False,False,False,False,False,False,False,False,False,3,False,False,True,False,False,False,False,False,False,False
4,1001020500,Autauga County,Alabama,0.18,0.00,0.03,0.00,0.02,0.70,0.04,0.00,0.11,0.74,0.13,0,0.0,False,False,NaN,False,0,0.0,False,False,10596.0,222.48,0.29,0.19,False,False,False,53.0,0.1419,False,55.0,0.0171,False,61.0,0.0002,25.0,3.0,False,False,73.0,5.0,False,False,False,38.0,2.0,False,69.0,9.24,False,61.0,0.30,False,43.0,220.21,False,6.0,False,46.0,21.0,False,1.0,0.0,48.0,186900.0,False,False,3955.0,51.0,True,False,NaN,0.95,0.04,False,56.0,1.08,False,64.0,0.09,False,13.0,0.09,NaN,NaN,False,False,False,False,False,10.0,0.00,False,55.0,2.22,False,37.0,919.0,False,34.0,919.0,False,31.0,500.0,False,41.0,79.40,False,22.0,125.0,False,54.0,1.0,False,26.0,3.0,False,29.0,20.0,62.0,15.0,40.0,7.0,94.0,2.0,5.0,False,False,False,NaN,NaN,NaN,0,6,False,False,False,False,False,False,False,False,False,False,3,False,False,True,False,False,False,False,False,False,False
5,1001020600,Autauga County,Alabama,0.18,0.00,0.00,0.00,0.01,0.74,0.04,0.01,0.14,0.70,0.15,0,0.0,False,False,NaN,False,0,0.0,False,False,3668.0,0.00,0.79,0.47,True,False,False,47.0,0.0926,False,62.0,0.0215,False,71.0,0.0003,68.0,11.0,False,False,78.0,32.0,False,False,False,57.0,3.0,False,67.0,9.16,False,38.0,0.19,False,47.0,259.61,False,49.0,False,43.0,20.0,False,25.0,7.0,18.0,103600.0,False,False,1937.0,24.0,True,False,NaN,0.21,0.00,False,46.0,0.62,False,60.0,0.08,False,17.0,0.10,NaN,NaN,False,False,False,False,False,87.0,0.22,False,46.0,1.53,False,75.0,1060.0,False,79.0,1340.0,False,75.0,740.0,False,89.0,73.09,False,59.0,85.0,False,31.0,0.0,False,70.0,6.0,False,75.0,45.0,83.0,25.0,67.0,14.0,94.0,6.0,10.0,False,False,False,NaN,NaN,NaN,0,3,False,False,True,False,False,False,False,False,False,False,6,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73052,56043000200,Washakie County,Wyoming,0.00,0.00,0.00,0.00,0.05,0.89,0.06,0.04,0.07,0.72,0.20,0,0.0,False,False,NaN,False,0,0.0,False,False,3051.0,0.00,0.44,0.26,False,False,False,77.0,0.6143,False,50.0,0.0142,False,52.0,0.0002,78.0,15.0,False,False,80.0,42.0,False,False,False,70.0,3.0,False,0.0,4.58,False,0.0,0.01,False,11.0,20.32,False,21.0,False,10.0,11.0,False,51.0,25.0,55.0,215300.0,False,False,374.0,5.0,True,False,NaN,0.70,0.01,False,1.0,0.00,False,2.0,0.00,False,22.0,0.13,NaN,True,False,False,False,True,False,12.0,0.00,False,6.0,0.00,False,35.0,910.0,False,47.0,1019.0,False,67.0,690.0,False,33.0,80.09,False,57.0,87.0,False,12.0,0.0,False,49.0,4.0,False,40.0,25.0,34.0,8.0,44.0,8.0,98.0,2.0,2.0,False,False,False,NaN,NaN,NaN,0,1,True,False,False,False,False,False,False,False,False,False,3,False,False,True,False,False,False,False,False,False,False
73053,56043000301,Washakie County,Wyoming,0.00,0.01,0.00,0.00,0.05,0.71,0.22,0.05,0.15,0.62,0.22,0,0.0,False,False,NaN,False,0,0.0,False,False,2482.0,0.00,0.61,0.35,False,False,False,12.0,0.0011,False,23.0,0.0041,False,38.0,0.0001,1.0,0.0,False,False,69.0,0.0,False,False,False,93.0,5.0,False,1.0,5.12,False,3.0,0.05,False,45.0,236.92,False,16.0,False,45.0,21.0,False,86.0,67.0,26.0,124300.0,False,False,6329.0,83.0,True,False,NaN,0.21,0.00,False,1.0,0.00,False,2.0,0.00,False,19.0,0.11,NaN,NaN,False,False,False,False,False,9.0,0.00,False,96.0,22.01,False,43.0,940.0,False,37.0,940.0,False,55.0,620.0,False,35.0,79.90,False,74.0,72.0,False,12.0,0.0,False,17.0,2.0,False,58.0,34.0,36.0,8.0,65.0,13.0,96.0,2.0,9.0,False,False,False,NaN,NaN,NaN,0,1,True,False,False,False,False,False,False,False,False,False,4,False,False,False,True,False,False,False,False,False,False
73054,56043000302,Washakie County,Wyoming,0.00,0.01,0.00,0.00,0.00,0.82,0.15,0.06,0.14,0.64,0.20,0,0.0,False,False,NaN,False,0,0.0,False,False,2494.0,9.35,0.49,0.29,False,False,False,85.0,1.0972,False,33.0,0.0067,False,39.0,0.0001,75.0,13.0,False,False,68.0,0.0,False,False,False,49.0,2.0,False,1.0,5.15,False,3.0,0.04,False,31.0,118.35,False,50.0,False,22.0,15.0,False,51.0,25.0,47.0,182600.0,False,False,6503.0,84.0,True,False,NaN,0.76,0.01,False,1.0,0.00,False,2.0,0.00,False,23.0,0.13,NaN,NaN,False,False,False,False,False,8.0,0.00,False,62.0,2.99,False,40.0,930.0,False,65.0,1170.0,False,83.0,810.0,False,18.0,81.80,False,52.0,91.0,False,70.0,4.0,False,45.0,4.0,False,46.0,28.0,62.0,15.0,43.0,8.0,96.0,1.0,5.0,False,False,False,NaN,NaN,NaN,0,8,False,False,False,False,False,False,True,False,False,False,4,False,False,False,True,False,False,False,False,False,False
73055,56045951100,Weston County,Wyoming,0.00,0.00,0.01,0.00,0.02,0.93,0.01,0.00,0.10,0.70,0.19,0,0.0,False,False,NaN,False,0,11.0,False,False,3294.0,71.08,0.58,0.33,False,False,False,52.0,0.1313,False,84.0,0.0577,False,81.0,0.0006,55.0,8.0,False,False,91.0,93.0,True,False,False,87.0,5.0,False,0.0,4.05,False,1.0,0.03,False,10.0,19.53,False,80.0,False,36.0,18.0,False,51.0,25.0,55.0,216100.0,False,False,480.0,7.0,True,False,NaN,0.59,0.00,False,13.0,0.07,False,10.0,0.01,False,11.0,0.07,False,True,False,False,False,True,False,10.0,0.00,False,5.0,0.00,False,35.0,910.0,False,44.0,1000.0,False,69.0,700.0,False,45.0,79.00,False,63.0,82.0,False,12.0,0.0,False,19.0,2.0,False,58.0,34.0,67.0,17.0,32.0,6.0,95.0,2.0,7.0,False,False,False,NaN,NaN,NaN,0,1,True,False,False,False,False,False,False,False,False,False,4,False,False,False,True,False,False,False,False,False,False
73056,56045951300,Weston County,Wyoming,0.00,0.00,0.00,0.00,0.00,0.98,0.00,0.00,0.17,0.63,0.19,0,0.0,False,False,NaN,False,0,0.0,False,False,3755.0,0.00,0.39,0.23,False,False,False,48.0,0.0989,False,77.0,0.0379,False,80.0,0.0005,48.0,7.0,False,False,94.0,96.0,True,False,False,63.0,3.0,False,0.0,4.22,False,5.0,0.05,False,32.0,127.13,False,43.0,False,16.0,13.0,False,72.0,48.0,32.0,140100.0,False,False,926.0,12.0,True,False,NaN,0.65,0.00,False,53.0,0.94,False,11.0,0.01,False,71.0,0.90,NaN,True,False,False,False,True,False,44.0,0.00,False,40.0,1.15,False,35.0,910.0,False,31.0,900.0,False,62.0,660.0,False,49.0,78.59,False,44.0,98.0,False,12.0,0.0,False,57.0,5.0,False,36.0,23.0,52.0,12.0,29.0,6.0,98.0,1.0,8.0,False,False,False,NaN,NaN,NaN,0,1,True,False,False,False,False,False,False,False,False,False,3,False,False,True,False,False,False,False,False,False,False

In [11]:
# "'has_datacenter ~ ' + ' + '.join(predictors)"
#logistic regression model with fixed effects

#list of dummy dataframes
dummy_list = [linguistic_isolation_dummies, perc_poverty_dummies]

#making list of dummy columns that predict a data center ??
for new_dummy in dummy_list:
    #dummies that predict data center
    dummy_predictors = [i for i in new_dummy.columns if i != 'has_datacenter']

#combining regular predictor columns with dummy predictor columns
all_predictors = predictors + dummy_predictors
print(all_predictors)

#fixed effects model
my_fixed_effects_model = statsmodels.formula.api.logit('has_datacenter ~ ' + ' + '.join(all_predictors), 
    data=cejst, subset=None, drop_cols=None).fit(disp=False) #, *args, **kwargs

my_fixed_effects_model.summary()

['perc_white', 'perc_poverty', 'pm_air', 'perc_unemployment', 'hazard_waste_prox', 'life_expectancy', 'perc_hispanic', 'perc_elderly', 'perc_children', 'perc_disadvantaged', 'population', 'loss_rate', 'flood_risk', 'energy_burden', 'diesel_exposure', 'traffic_prox', 'travel_barriers', 'housing_burden', 'house_value', 'pavement_cropland', 'no_plumbing', 'superfund_prox', 'asthma', 'diabetes', 'heart_disease', 'household_income_compared', 'linguistic_isolation', 'no_hs_degree', 'perc_poverty_1', 'perc_poverty_2', 'perc_poverty_3', 'perc_poverty_4', 'perc_poverty_5', 'perc_poverty_7', 'perc_poverty_8', 'perc_poverty_9', 'perc_poverty_10', 'perc_poverty_11']

/Users/charlottemeyer/anaconda3/envs/.da_401/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:         has_datacenter   No. Observations:                59078
Model:                          Logit   Df Residuals:                    59039
Method:                           MLE   Df Model:                           38
Date:                Thu, 30 Apr 2026   Pseudo R-squ.:                 0.04832
Time:                        21:31:25   Log-Likelihood:                -1823.1
converged:                      False   LL-Null:                       -1915.7
Covariance Type:            nonrobust   LLR p-value:                 3.024e-21
=============================================================================================
                                coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------
Intercept                    -1.7958      2.225     -0.807      0.420      -6.157       2.565
perc_poverty_1[T.True]        0.6221      1.023      0.608      0.543      -1.383       2.627
perc_poverty_2[T.True]        0.0299      0.859      0.035      0.972      -1.654       1.714
perc_poverty_3[T.True]        0.1623      0.672      0.242      0.809      -1.155       1.479
perc_poverty_4[T.True]        0.1244      0.487      0.255      0.799      -0.831       1.080
perc_poverty_5[T.True]       -0.5268      0.348     -1.512      0.131      -1.210       0.156
perc_poverty_7[T.True]       -0.0600      0.384     -0.156      0.876      -0.812       0.692
perc_poverty_8[T.True]       -0.0538      0.597     -0.090      0.928      -1.225       1.117
perc_poverty_9[T.True]        0.3292      0.873      0.377      0.706      -1.382       2.041
perc_poverty_10[T.True]      -5.2058     21.725     -0.240      0.811     -47.786      37.374
perc_poverty_11[T.True]     -13.8754   7145.720     -0.002      0.998    -1.4e+04     1.4e+04
perc_white                   -0.3747      0.504     -0.744      0.457      -1.362       0.612
perc_poverty                 -0.0398      2.489     -0.016      0.987      -4.918       4.838
pm_air                       -0.0395      0.040     -0.989      0.322      -0.118       0.039
perc_unemployment             0.0066      0.021      0.311      0.756      -0.035       0.048
hazard_waste_prox             0.0271      0.017      1.613      0.107      -0.006       0.060
life_expectancy               0.0059      0.022      0.268      0.789      -0.037       0.049
perc_hispanic                 0.1950      0.507      0.384      0.701      -0.800       1.190
perc_elderly                 -3.7759      1.747     -2.161      0.031      -7.200      -0.352
perc_children                -1.3376      1.779     -0.752      0.452      -4.824       2.149
perc_disadvantaged            0.0033      0.002      1.396      0.163      -0.001       0.008
population                -7.052e-05   2.99e-05     -2.361      0.018      -0.000    -1.2e-05
loss_rate                    34.5753     45.102      0.767      0.443     -53.822     122.973
flood_risk                   -0.0060      0.004     -1.360      0.174      -0.015       0.003
energy_burden                -0.4081      0.077     -5.322      0.000      -0.558      -0.258
diesel_exposure              -0.2765      0.358     -0.773      0.440      -0.978       0.425
traffic_prox               1.925e-05   3.32e-05      0.580      0.562   -4.58e-05    8.43e-05
travel_barriers              -0.0019      0.003     -0.717      0.473      -0.007       0.003
housing_burden               -0.0207      0.010     -2.147      0.032      -0.040      -0.002
house_value                -1.42e-06    4.2e-07     -3.384      0.001   -2.24e-06   -5.97e-07
pavement_cropland             0.0020      0.003      0.704      0.482      -0.004       0.008
no_plumbing                   0.0944      0.218      0.432      0.666      -0.334       0.523
superfund_prox                0.1675      0.148      1.131      0.258      -0.123       0.458
asthma                       -0.0010      0.003     -0.303      0.762      -0.007       0.005
diabetes                     -0.0056      0.007     -0.831      0.406      -0.019       0.008
heart_disease                -0.0006      0.007     -0.092      0.927      -0.014       0.013
household_income_compared    -0.0072      0.003     -2.462      0.014      -0.013      -0.001
linguistic_isolation          0.0074      0.003      2.318      0.020       0.001       0.014
no_hs_degree                 -0.0071      0.012     -0.566      0.571      -0.032       0.017
=============================================================================================
"""

In [12]:
#list of columns that had low p-values in logit model
feature_columns_significant = ["perc_poverty",
                               "perc_hispanic",
                               "perc_elderly",
                               "population",
                               "loss_rate",
                               "travel_barriers",
                               "house_value",
                               "risk_facilities_prox",
                               "leaky_storage_tanks",
                               "asthma"]

new_significant = ["population", 
                   "energy_burden",
                   "risk_facilities_prox",
                   "linguistic_isolation"]

In [14]:
#splittling into testing and training
#X_train, X_test, y_train, y_test = train_test_split(
#    X, y, test_size=0.25, random_state=26
#)

In [15]:
#still need this for the multicollinearity test
X = cejst[predictors]
y = cejst["has_datacenter"]

#dropping all rows with NaN in X columns
X = X.dropna()
#Keep y aligned with X
y = y.loc[X.index]  

# Verify they match
print(f"X shape: {X.shape}, y shape: {y.shape}")
#verify no na's
print(X.isnull().sum())

X shape: (59078, 28), y shape: (59078,)
perc_white                   0
perc_poverty                 0
pm_air                       0
perc_unemployment            0
hazard_waste_prox            0
life_expectancy              0
perc_hispanic                0
perc_elderly                 0
perc_children                0
perc_disadvantaged           0
population                   0
loss_rate                    0
flood_risk                   0
energy_burden                0
diesel_exposure              0
traffic_prox                 0
travel_barriers              0
housing_burden               0
house_value                  0
pavement_cropland            0
no_plumbing                  0
superfund_prox               0
asthma                       0
diabetes                     0
heart_disease                0
household_income_compared    0
linguistic_isolation         0
no_hs_degree                 0
dtype: int64

In [16]:
#code adapted from https://www.statology.org/how-to-test-for-multicollinearity-with-statsmodels/
#testing for multicollinearity

from statsmodels.stats.outliers_influence import variance_inflation_factor

# Compute VIF
vif_data = pd.DataFrame()
vif_data["feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i)
                   for i in range(X.shape[1])]

print(vif_data)

                      feature         VIF
0                  perc_white   28.306099
1                perc_poverty   36.799589
2                      pm_air   33.984501
3           perc_unemployment    4.468159
4           hazard_waste_prox    2.869737
5             life_expectancy  169.153638
6               perc_hispanic    5.166315
7                perc_elderly   20.266485
8               perc_children   15.103475
9          perc_disadvantaged    4.392691
10                 population    6.210092
11                  loss_rate    1.216665
12                 flood_risk    1.644375
13              energy_burden   10.629757
14            diesel_exposure    6.446378
15               traffic_prox    1.722776
16            travel_barriers    6.186916
17             housing_burden   18.805930
18                house_value    5.079448
19          pavement_cropland    7.096850
20                no_plumbing    4.452115
21             superfund_prox    1.318499
22                     asthma   11.092293
23                   diabetes   41.914581
24              heart_disease   46.210753
25  household_income_compared   24.708562
26       linguistic_isolation    8.683419
27               no_hs_degree   10.126567